# Project information
site_name: СИСADМИН.blog
site_description: Собираю стеки (docker, swarm, docker-compose). Пишу автоматизации
site_author: ifilatov
site_url: https://blog.filatovz.ru
analytics: '64995766'

theme:
  name: null
  custom_dir: material
  language: ru
  favicon: 'images/favicon.ico'
  logo: 'images/favicon.png'
  features:
    - search.suggest
    - navigation.top
    - tabs
  palette:
    primary: white
    accent: red
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: material/library
    repo: fontawesome/brands/git-alt

plugins:
  - search
      lang:
        - en
        - ru
  - awesome-pages
  - blog:
      format: "(%m/%d/%y)"
      text-align: "left"
extra:
  search:
    language: 'en, ru'
extra_css:
  - css/custom.css
markdown_extensions:
  - admonition
  - meta
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde
  - pymdownx.inlinehilite
  - pymdownx.highlight
  - pymdownx.keys